"""Signal 2 — LLM-as-judge (Groq).

Pydantic enforces the response shape: label ∈ {"AI", "Human"}, non-empty
reasoning, confidence ∈ [0, 1]. The schema is generated from the model and
injected into the prompt so the contract lives in one place.

Conversion to a unified AI-direction score:
    llm_ai_score = confidence       if label == "AI"
                 = 1 - confidence    if label == "Human"

Returns None on any failure (network, malformed JSON, schema violation) so the
combiner can apply the §1 tie-breaking rule (fall back to stylo alone, force
label = "uncertain").
"""
from __future__ import annotations

import json
import os
from typing import Literal, Optional

from groq import Groq
from pydantic import BaseModel, Field

_MODEL = "llama-3.3-70b-versatile"


class JudgeResponse(BaseModel):
    """The exact JSON contract the judge must return."""
    label: Literal["AI", "Human"]
    reasoning: str = Field(min_length=1)
    confidence: float = Field(ge=0.0, le=1.0)


_SYSTEM_PROMPT = f"""\
You are a forensic text classifier. Given a piece of text, decide whether it \
was written by a human or generated by an AI language model. Focus on \
holistic cues: semantic coherence, sentiment authenticity, voice consistency, \
and overall flow — not surface features like punctuation or word choice alone.

Respond with a single JSON object matching this schema, and nothing else:
{json.dumps(JudgeResponse.model_json_schema(), indent=2)}
"""


def judge(text: str) -> Optional[dict]:
    """Run Signal 2. Returns the judge dict or None on any failure."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return None

    try:
        client = Groq(api_key=api_key)
        completion = client.chat.completions.create(
            model=_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user",   "content": text},
            ],
            response_format={"type": "json_object"},
            temperature=0.0,
        )
        response = JudgeResponse.model_validate_json(completion.choices[0].message.content)
    except Exception:
        # §1 fallback: any failure (network, malformed JSON, schema violation,
        # missing/out-of-range fields) → judge result is None, combiner forces "uncertain".
        return None

    llm_ai_score = (
        response.confidence if response.label == "AI" else 1.0 - response.confidence
    )
    return {
        "llm_label":      response.label,
        "llm_confidence": response.confidence,
        "llm_rationale":  response.reasoning,
        "llm_ai_score":   llm_ai_score,
    }
